# -*- coding: utf-8 -*-
"""exam by Watcharaphon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8xpyjaGvouhljD6iEFpPBtEip-TgjxZ
"""

def my_function():
  arrTotal = [15, -2, 16, 8, 10]
  len(arrTotal)
  numMin = int(arrTotal[0])
  for x in range(len(arrTotal)):
    if arrTotal[x] < numMin and arrTotal[x] > 0:
      numMin = arrTotal[x]
    else:
      print("Please enter a positive integer number.")
      break;
  if (1 / numMin) *  numMin != 1:
    print(numMin)
  else:
    print("No Result!!!")
  
my_function()