# -*- coding: utf-8 -*-
"""exam by Wanwisa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CbOVMD6IVPUwDjia0-J0qYRgLJ87L31r
"""

def My_function():
  numbers = input("Enter 4 numbers and leave spaces : ").split()[:4]
  numArry = [int(number) for number in numbers]
  total = 0
  for i in range(len(numArry)):
    if numArry[i] == max(numArry) or numArry[i] == min(numArry):
      continue
    else:
      total = total + numArry[i]
  print ("Min number :",min(numArry), "\nMax number :",max(numArry), "\nTotal number :",total)
My_function()