# -*- coding: utf-8 -*-
"""ExamByPalm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y0VA2i8lm7gPO10t0JXim0FK2qUtdLkF
"""

#กรอกตัวเลขจากน้อยไปหามาก
def myfunction():
  numbers = input("กรอกตัวเลข 5 ตัวและเว้นวรรค: ").split()
  numbers = [int(number) for number in numbers]
  if numbers[0] < numbers[1] and numbers[1] < numbers[2] and numbers[2] < numbers[3]  and numbers[3] < numbers[4]:
    min = 'จริง'
  else:
    min = 'เท็จ'
  print(numbers,'ตัวเลขที่ท่านกรอกจากน้อยไปหามากเป็น',min)
myfunction()