# -*- coding: utf-8 -*-
"""Yailanee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15N43rJwMPZwuXbwQ3z4opt84IaHvCYT5
"""

def Yai_function():
  a = input("Enter Number ")
  x = 10
  sumTotal = x ^ 3
  if sumTotal == a:
    print(x)
  else:
    print("Not found")
Yai_function()