# -*- coding: utf-8 -*-
"""คำนวนพื้นที่ภายในสี่เหลี่ยมผืนผ้า.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f5edt_BOGklsn9oHCiCeneCHcbzMtA5G
"""

#-------------------------------------------------------
# Author    : Computer for Education
# Author URI: https://www.computerforedu.com
# Facebook  : https://www.facebook.com/computerforedu
#-------------------------------------------------------
 
width = float(input("กรอกตัวเลขความกว้าง : "))
xlong = float(input("กรอกตัวเลขความยาว :  "))
area = width * xlong 
 
print("พื้นที่สี่เหลี่ยมผืนผ้ามีค่าเท่ากับ %.2f" % area)